baseurl = "https://metu-sparg.netlify.app"
copyright = "&copy; {year} METU SPARG"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
hasCJKLanguage = false
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
removePathAccents = true
summaryLength = 30
title = "METU Spatial Audio Research Group (METU SPARG)"
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "lanczos"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = false
[markup.tableOfContents]
endLevel = 3
startLevel = 2
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
[[module.imports]]
path = "github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
section = ["HTML", "RSS"]
[permalinks]
authors = "/author/:slug/"
categories = "/category/:slug/"
publication_types = "/publication-type/:slug/"
tags = "/tag/:slug/"
[related]
includeNewer = true
threshold = 80.0
toLower = true
[[related.indices]]
name = "tags"
weight = 80.0
[[related.indices]]
name = "categories"
weight = 70.0
[taxonomies]
author = "authors"
category = "categories"
publication_type = "publication_types"
tag = "tags"
